org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
mapping_channel=parchment
mapping_version=2024.11.17-1.21.1

## Forge
forge_version=52.1.0
forge_version_range=[0,)
forge_loader_version_range=[0,)

## Neoforge
neo_version=21.1.249
neoforge_loader_version_range=[1,)

## Mod Properties
mod_id=oldworldfantasy
mod_name=Old World Fantasy
mod_license=All Rights Reserved
mod_version=0.3.4-1.21
mod_group_id=net.jaeger.oldworldfantasy
mod_authors=Jaeger
mod_description=Old World Fantasy is fantasy mod based in the Warhammer Fantasy universe.\nThis Mod tries to bring the world of Warhammer in an authentic way.
