architectury {
    common rootProject.enabled_platforms.split(',')
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    compileOnly "software.bernie.geckolib:geckolib-common-${minecraft_version}:${geckolib_version}"
}
